# Generated by Django 6.0.3 on 2026-03-25 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the department name', max_length=200, verbose_name='Department Name')),
                ('building_location', models.CharField(blank=True, help_text='Enter the building location', max_length=200, verbose_name='Building Location')),
                ('head_of_department', models.CharField(help_text='Enter the head of department', max_length=200, verbose_name='Head of Department')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the level of study', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the profesor name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the student first name', max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter the student last name', max_length=200, verbose_name='Last Name')),
                ('student_id', models.CharField(help_text='Enter the student ID', max_length=50, unique=True, verbose_name='Student ID')),
                ('enrollment_year', models.IntegerField(blank=True, help_text='Enter the enrollment year', null=True, verbose_name='Enrollment Year')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='Enter the course code', max_length=200, verbose_name='Course Code')),
                ('title', models.CharField(help_text='Enter the course title', max_length=200, verbose_name='Course Title')),
                ('description', models.TextField(blank=True, help_text='Enter the course description', verbose_name='Course Description')),
                ('topic', models.CharField(blank=True, help_text='Enter the course topic', max_length=255, verbose_name='Course Topic')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
                ('academic_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.level')),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(help_text='Enter the class group ID', max_length=50, unique=True, verbose_name='Class Group ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FULL', 'Full')], default='OPEN', max_length=20, verbose_name='Enrollment Status')),
                ('schedule', models.CharField(blank=True, help_text='Enter the class schedule (e.g., Mon/Wed/Fri 10:00-11:00)', max_length=255, verbose_name='Class Schedule')),
                ('maxStudents', models.IntegerField(help_text='Enter the maximum number of students', verbose_name='Maximum Students')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='catalog.course')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='catalog.profesor')),
                ('enrolled_students', models.ManyToManyField(blank=True, related_name='classes', to='catalog.student')),
            ],
        ),
    ]
