# Generated by Django 6.0.3 on 2026-04-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_enrollmentproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
