# Generated by Django 6.0.3 on 2026-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_merge_20260507_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Enrollment Status'),
        ),
    ]
